name: Feature Request
description: Suggest a new feature or enhancement for Ollama GUI
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: ["jblancuzzi"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - User Interface
        - Chat/Messaging
        - Model Management
        - Settings/Configuration
        - Export/Import
        - Performance
        - Accessibility
        - Security
        - API/Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Essential for my use case
        - Critical - Blocking current usage
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [scenario], I need [capability] because [reason]
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: Mockups/Examples
      description: If you have mockups, wireframes, or examples from other applications, please share them
      placeholder: You can drag and drop images here or provide links to examples

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share them
      placeholder: Technical suggestions, API requirements, UI considerations, etc.

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor UI change or setting
        - Moderate - New panel or significant feature
        - Complex - Major architectural change
        - I'm not sure
    validations:
      required: false

  - type: checkboxes
    id: related-features
    attributes:
      label: Related Features
      description: Would this feature work well with or require other features?
      options:
        - label: This feature would complement existing model management
        - label: This feature requires changes to the chat interface
        - label: This feature needs new settings/configuration options
        - label: This feature affects data export/import
        - label: This feature impacts performance
        - label: This feature requires API changes

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that would help us understand this request better

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all applicable boxes
      options:
        - label: I have searched existing issues for similar feature requests
          required: true
        - label: I have provided clear use cases for this feature
          required: true
        - label: I understand this is a feature request, not a bug report
          required: true
        - label: I am willing to help test this feature if implemented
          required: false
